# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0036d5ac3046bb4187d1e79f58e7693ab2574538599845cecf49c16b686cbb3ac993603206e3830795cc7510874036b80857305e4af636be83f186a7874a272e

test:
  secret_key_base: d08cf8b514bc80ff9e8486f2d4193b5f85887fd16c88e919b460d569308cd979ee82c8aed3acfa849cedfb657168df000133b9c8bf3bbbe4a8d564fb6b60a6b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
